name: Create PR to Development

on:
  push:
    branches-ignore:
      - 'development'
      - 'master'

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Create pull request to development
      run: |
        BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
        if [ "$BRANCH_NAME" != "development" ] && [ "$BRANCH_NAME" != "master" ]; then
          gh pr create \
            --base development \
            --head "$BRANCH_NAME" \
            --title "Automated PR from $BRANCH_NAME to development" \
            --body "This pull request was automatically created by GitHub Actions."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
