name: Create PR to Master After Deployment

on:
  push:
    branches:
      - development

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Create pull request to master
      run: |
        BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
        if [ "$BRANCH_NAME" = "development" ]; then
          gh pr create \
            --base master \
            --head "$BRANCH_NAME" \
            --title "Automated PR from development to master" \
            --body "This pull request was automatically created by GitHub Actions after deployment."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
